<body >
    <div style="direction:rtl;line-height:300%;background-color:rgb(255, 255, 255);">
            <img src="./images/Fanni-Transparent.png" style="position:reletive;margin-top:25pt;float:right;" width="200" height="200"/>
    <img src="./images/University_of_Tehran_logo.svg" style="position:reletive;margin-top:25pt;margin-left:20pt;float:left;" width="150" height="150"/>
		<div align=center>
			<font  size=5 >
				<p></p>
				<p></p>
                <br>
                 بسمه تعالی
				<p></p>
			</font>
		</div>
        <div align=center >
                        <font size=30 >
                            <br>
                            گزارش همورک چهارم
                        </font>
         </div>
           <div align=center >
                        <font size=3 >
                            <br>
تهیه و تنظیم : سپهر سعیدپور
                            <br>
۸۱۰۱۹۶۶۵۴
                        </font>
        </div>
    </div>
</body>

# Q1

In [2]:
import pandas as pd
import numpy as np

# پیاده‌سازی K means

In [221]:
class Kmeans(object):
    def __init__(self, data, num_clusters):
        
        self.k = num_clusters
        self.data = data
    
    def get_initial_centroids(self,seed=None):
        if seed != None:  
            np.random.seed(seed)
        
        n = self.data.shape[0]  
        rand_indices = (np.random.choice(range(n), self.k , replace = False))

        centroids = self.data.iloc[rand_indices, :]

        return np.array(centroids)
    
    
    def get_euclidean_distance(self,B):
        A = np.array(self.data)
        return np.array([[ np.linalg.norm(i-j) for j in B] for i in A])
    
    
    def get_clusters(self, centroids):
        
        clusters = {}
        distance_matrix = self.get_euclidean_distance(centroids)
        closest_cluster_ids = np.argmin(distance_matrix, axis=1)

        for i in range(self.k):
            clusters[i] = []

        for i, cluster_id in enumerate(closest_cluster_ids):
            clusters[cluster_id].append(self.data.iloc[i])
    
        return clusters , closest_cluster_ids
    
    def has_centroids_covered(self,previous_centroids, centroids, threshold):
        
        distances_between_old_and_new_centroids = get_euclidean_distance(previous_centroids, centroids)
        centroids_covered = (np.max(distances_between_old_and_new_centroids.diagonal()) <= threshold)

        return centroids_covered
    
    
    
    def train(self,threshold):
        
        centroids = self.get_initial_centroids(10)

        centroids_covered = False

        while not centroids_covered:
            previous_centroids = centroids
            clusters, ids = self.get_clusters(previous_centroids)

            centroids = np.array([np.mean(clusters[key], axis=0) for key in sorted(clusters.keys())])

            centroids_covered = self.has_centroids_covered(previous_centroids, centroids, threshold)

        return centroids, ids
        

In [239]:
train_data = pd.read_csv('Q1/Train_Data.csv', header= None)
train_labels = pd.read_csv('Q1/Train_Labels.csv', header= None)[0]

In [275]:
model = Kmeans(train_data, num_clusters= 3)

labels = model.train(0)[1]

labels = pd.Series(labels).replace({1 : 0 , 2: 1, 0 : 2})

 # پیاده‌سازی k means به وسیله کتابخانه 

In [276]:
from sklearn.cluster import KMeans

km = KMeans(
    n_clusters=3, init='random',
    n_init=10, max_iter=300, 
    tol=1e-04, random_state=10
)
y_km = km.fit_predict(train_data)

In [277]:
y_km

array([0, 1, 0, 0, 2, 2, 1, 2, 0, 2, 1, 1, 0, 1, 2, 2, 0, 2, 1, 1, 0, 2,
       2, 1, 2, 2, 1, 2, 0, 0, 0, 1, 0, 1, 2, 2, 0, 0, 1, 0, 1, 2, 0, 2,
       1, 2, 2, 2, 0, 2, 0, 2, 2, 1, 2, 2, 2, 1, 2, 0, 0, 0, 1, 2, 0, 0,
       0, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 1, 2, 2, 2, 1, 2, 0, 0, 0, 2, 0,
       0, 1, 0, 2, 0, 2, 2, 2, 0, 1, 1, 0, 1, 2, 2, 2, 1, 0, 1, 1, 2, 2,
       1, 2, 2, 0, 2, 2, 2, 2, 1, 0, 0, 0, 2, 2, 1, 2, 2, 0, 1, 2, 2, 0,
       1, 0, 2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 1])

#  محاسبه Confusion matrix

In [279]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_km, labels)

array([[47,  0,  0],
       [ 0, 34,  0],
       [ 1,  0, 63]], dtype=int64)

# Q3

<img src="./2.jpg" width="400">

# Q2

In [208]:
from scipy.spatial import distance_matrix

data = [[12,9,7], [-2, 4, 4], [15, 0, 1], [3, -1, 2], [11, 4, 9]]

distance_matrix(data,data)

array([[ 0.        , 15.16575089, 11.22497216, 14.35270009,  5.47722558],
       [15.16575089,  0.        , 17.72004515,  7.34846923, 13.92838828],
       [11.22497216, 17.72004515,  0.        , 12.08304597,  9.79795897],
       [14.35270009,  7.34846923, 12.08304597,  0.        , 11.74734012],
       [ 5.47722558, 13.92838828,  9.79795897, 11.74734012,  0.        ]])

<img src="./3.jpg" width="400">

شماره سوال به اشتباه درج شده‌است

#  Q4

In [659]:
import scipy
from scipy.stats import multivariate_normal
import matplotlib.pyplot as plt
from sklearn import preprocessing
min_max_scaler = preprocessing.StandardScaler()

In [660]:
train_data = pd.read_csv('Q4/Train_Data.csv', header= None)
train_labels = pd.read_csv('Q4/Train_Labels.csv', header= None)[0]

train_data = pd.DataFrame(min_max_scaler.fit_transform(train_data))

test_data = pd.read_csv('Q4/Test_Data.csv', header= None)
test_labels = pd.read_csv('Q4/Test_Labels.csv', header= None)[0]

test_data = pd.DataFrame(min_max_scaler.fit_transform(test_data))

# پیاده‌سازی تابع زیر

\begin{aligned}
     \hat f(x)  & = argmax_g  Pr(g | X = x) 
     \\
     & = argmax_g  \frac{Pr(x | g) p(g)}{p(x)} 
     \\
     & = argmax_g  Pr(x | g) p(g)
 \end{aligned}

#  بدون در نظر گرفتن دانش اولیه

\begin{aligned}
     \hat f(x)  & =   argmax_g  Pr(x | g) 
 \end{aligned}

In [664]:
def predict_Bayes_class(X,mu_list,cov_list): 

    scores_list = []
    classes = len(mu_list)
    
    for p in range(classes):
        score = multivariate_normal.pdf(X, mean=mu_list[p], cov=cov_list[p])
        scores_list.append(score)
             
    return np.argmax(scores_list)

In [665]:
mu_list = []
cov_list = []
prior_list = []

for i in sorted(train_labels.unique()):
    data = train_data[train_labels == i]
    mu = data.mean()
    cov = data.cov()
    prior = np.mean(train_labels == i)
    
    mu_list.append(mu)
    cov_list.append(cov)
    prior_list.append(prior)

In [666]:
predicted = test_data.apply(lambda x: predict_Bayes_class(x, mu_list, cov_list), axis= 1)

In [667]:
confusion_matrix(test_labels, predicted)

array([[258,   0,   2,  37,   1,   0,  26,   0,   5,   0],
       [  2, 285,   1,  50,   3,   0,   5,   0,   0,   0],
       [  8,   0, 248,   6,  61,   0,  35,   0,  10,   0],
       [ 16,   4,   3, 324,  11,   0,  13,   0,   4,   0],
       [  2,   0,  21,  24, 286,   0,  24,   0,   8,   0],
       [  2,   0,   0,   0,   0, 344,   0,   0,   1,   3],
       [ 68,   0,  22,  17, 104,   0,  97,   0,  14,   0],
       [  0,   0,   0,   0,   0, 298,   0,   0,   0,  33],
       [  4,   0,   1,   7,   0,   1,   6,   0, 350,   0],
       [  1,   0,   0,   0,   0,  24,   0,   0,   1, 319]], dtype=int64)

In [668]:
print(np.mean(test_labels == predicted))

0.7174285714285714


#  با در نظر گرفتن دانش اولیه

\begin{aligned}
\hat f(x)  & = argmax_g  Pr(g | X = x) p(g)
 \end{aligned}


In [669]:
def predict_Bayes_class_prior_knowledge(X,mu_list,cov_list, prior_list): 

    scores_list = []
    classes = len(mu_list)
    
    for p in range(classes):
        score = multivariate_normal.pdf(X, mean=mu_list[p], cov=cov_list[p]) * prior_list[p]
        scores_list.append(score)
             
    return np.argmax(scores_list)

In [670]:
predicted_prior = test_data.apply(lambda x: predict_Bayes_class_prior_knowledge(x,mu_list,cov_list, prior_list), axis= 1)

In [671]:
confusion_matrix(test_labels, predicted_prior)

array([[258,   0,   2,  37,   1,   0,  26,   0,   5,   0],
       [  2, 285,   1,  50,   3,   0,   5,   0,   0,   0],
       [  8,   0, 248,   6,  61,   0,  35,   0,  10,   0],
       [ 16,   4,   3, 324,  11,   0,  13,   0,   4,   0],
       [  2,   0,  21,  24, 286,   0,  24,   0,   8,   0],
       [  2,   0,   0,   0,   0, 344,   0,   0,   1,   3],
       [ 68,   0,  22,  17, 104,   0,  97,   0,  14,   0],
       [  0,   0,   0,   0,   0, 298,   0,   0,   0,  33],
       [  4,   0,   1,   7,   0,   1,   6,   0, 350,   0],
       [  1,   0,   0,   0,   0,  24,   0,   0,   1, 319]], dtype=int64)

In [672]:
print(np.mean(test_labels == predicted_prior))

0.7174285714285714


 از آنجایی که عملا توزیع لیبل‌ها در داده ما شبیه به هم هستند. اضافه کردن فرض پیشین تاثیری بر دقت نخواهد داشت.

# Q5

In [17]:
from sklearn.model_selection import train_test_split
import operator

In [188]:
df = pd.read_csv('Q5/income_Q5.csv')
train, test = train_test_split(df, test_size=0.2, random_state = 20)
train = train.reset_index(drop = True)
test = test.reset_index(drop = True)

## Naive Bayes

$$ P(evidences \mid class=A) = P(evidence_1 \mid class=A) * P(evidence_2 \mid class=A) * ... * P(evidence_n \mid class=A) $$

$$ P(class=A \mid evidences) = \frac{P(evidence_1 \mid class=A) * P(evidence_2 \mid class=A) * ... * P(evidence_n \mid class=A) \, P(class=A)}{P(evidences)} $$

In [195]:
class NaiveBayes(object):
            
    def fit(self, X, target):
        
        self.class_probs = {}
        self.class_numbers = {}
        labels = X[target].unique()
        for l in labels:
            self.class_probs[l] = np.mean(train[target] == l)
            self.class_numbers[l] = np.sum(train[target] == l)
                    
        self.features = X.columns.drop(target)
            
        self.features_probs = {}
        
        for l in labels:
            self.features_probs[l] = {}
            for f in self.features:
                self.features_probs[l][f] = {}
                
                
        for l in labels:
            for f in self.features:
                vals = X[f].unique()
                for val in vals:
                    self.features_probs[l][f][val] = (np.sum(np.logical_and( X[f]==val, X[target]==l)) + 1) / (self.class_numbers[l] + len(vals))
    
    def predict_a_datapoint(self, X_test):
        
        log_class_probs ={k: np.log10(v) for k, v in self.class_probs.items()}
        
        for f in self.features:
            value = X_test[f]
            for label, v in log_class_probs.items():
                log_class_probs[label] += np.log10(self.features_probs[label][f][value])
                    
        return max(log_class_probs.items(), key=operator.itemgetter(1))[0]
    
    def predict(self, X_test):
        prediction = []
        for i in X_test.index:
            predict_income = self.predict_a_datapoint(X_test.iloc[i])
            prediction.append(predict_income)
        return pd.Series(prediction)

In [205]:
model = NaiveBayes()

model.fit(train, 'income')

prediction = model.predict(test)

In [206]:
from sklearn.metrics import confusion_matrix , accuracy_score

confusion_matrix(test.income, prediction)

array([[6159, 1226],
       [ 624, 1760]], dtype=int64)

In [207]:
print(accuracy_score(test.income, prediction))

0.8106254478452247


# Laplace Smoothing 


 
 \begin{aligned}
      P(w|c)=\frac{\text{count}(w,c) +1}{\text{count}(c) + |V|}
 \end{aligned}

این روش، روش بسیار مهمی است، از این جهت که باعث می‌شود ما بتوانیم تاثیر احتمال‌های صفر یعنی در واقع داده‌هایی که در یک کلاس خاص ندیده‌ایم را از بین ببریم و از آن داده‌هایی که مشاهده نشدند هم استفاده کنیم تا مدل درست‌تر و با دقت‌تری داشته باشیم.